apiVersion: apps/v1
kind: Deployment
metadata:
  name: tfserving-trex-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tfserving-trex
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: tfserving-trex
    spec:
      containers:
        - image: ivancanaveral/trex:first
          imagePullPolicy: Always
          name: tfserving-trex
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "200m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "200Mi"