apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: tfserving-trex-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: tfserving-trex-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70